[package]
name = "wirecrab"
version = "0.1.0"
authors = ["Vedran Karacic <karacicvedran@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.7.0"
etherparse = "0.9.0"
libc = "0.2.81"
